[package]
name = "grammar"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@ens-rennes.fr>"]
edition = "2018"

[dependencies]
source-span = "*"
once_cell = "*"
automaton = { path = "../../data-structures/automaton" }
range-map = { path = "../../data-structures/range-map" }

utf8-decode = "*"
stderrlog = "*"
log = "*"
clap = {version = "*", features = ["yaml"] }
