[package]
name = "grammar"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@ens-rennes.fr>"]
edition = "2018"

[dependencies]
source-span = "*"

utf8-decode = "*"
stderrlog = "*"
log = "*"
clap = {version = "*", features = ["yaml"] }
