[package]
name = "grammar"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@ens-rennes.fr>"]
edition = "2018"

[dependencies]
source-span = "*"
once_cell = "*"
btree-slab = { path = "../../data-structures/btree-slab" }
range-map = { path = "../../data-structures/range-map" }

proc-macro2 = "*"
quote = "*"

utf8-decode = "*"
stderrlog = "*"
log = "*"
clap = {version = "*", features = ["yaml"] }
